### ISSUE TITLE
SPI support

### ISSUE THREAD

**Issue by neilgall** [rp-rs/rp-hal#10]
There are two SPI interfaces described in section 4.4 of the [datasheet](https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf)

Both interfaces support:
* Master or slave mode
* Programmable clock and word size
* Programmable choice of GPIO pins
* Separate transmit, receive, overflow and receive timeout interrupts

**Comment by hmvp** [comment]
I'd like to make start with this if nobody minds..

**Comment by neilgall** [comment]
Yes, I started back in February but haven't had much time.

**Comment by anall** [comment]
@hmvp I was actually thinking of looking at this as an example of something that makes use of the fancy GPIO refactor, but if you've made progress or really want to work on this feel free to continue and I'll refactor afterward — but I can't guarantee how much will be left.

**Comment by hmvp** [comment]
@anall I pushed what I have so far in https://github.com/rp-rs/rp-hal/pull/50 I don't own a scope so its a bit hard to figure out why it is not working properly. So I don't mind you finishing it.

I was thinking on rebasing it to your gpio branch since i needed funcsel.

**Comment by anall** [comment]
That's actually a decent start. I left a review on #50 but minimal changes were needed to make it work.

**Comment by 9names** [comment]
Initial implementation merged in #50
