### ISSUE TITLE
DMA on the way!

### ISSUE THREAD

**Issue by AsafFisher** [rp-rs/rp-hal#13]
Implement the DMA api for all the peripherals  :memo:

**Comment by tdittr** [comment]
Things I had on my list for the DMA:
- Example: https://docs.rs/stm32f1xx-hal/0.7.0/stm32f1xx_hal/dma/index.html
- Traits: https://crates.io/crates/embedded-dma

**Comment by AsafFisher** [comment]
Thank you for the guidance! I will look in to it (:

**Comment by AsafFisher** [comment]
I dont like `https://crates.io/crates/embedded-dma`'s traits why should I follow them?

**Comment by tdittr** [comment]
Well, I guess it would allow more interoperation, similar to the embedded-hal traits.

**Comment by maximeborges** [comment]
What is the status of this implementation?

**Comment by 9names** [comment]
@maximeborges The branch where this work took place is https://github.com/rp-rs/rp-hal/tree/rp-dma
It has not been touched in 7 months. I would call the status of this implementation "abandoned".
Use it as a starting point if you wish, but if you a need for DMA I suggest starting a new branch and working on it rather than waiting for this to be finished.

**Comment by mgottschlag** [comment]
See #209 for a more complete take on DMA which is already usable.

**Comment by lightsing** [comment]
How is it going? Is there any working on progress?

**Comment by 9names** [comment]
No progress

**Comment by eloraiby** [comment]
@AsafFisher any news on this one?

**Comment by 9names** [comment]
AsafFisher has not been active on this project in over a year.
No progress to report

**Comment by ogoffart** [comment]
I have been using the PR #209 in my project (details in this comment: https://github.com/rp-rs/rp-hal/pull/209#issuecomment-1156582772 ) I have rebased the change to the recent branch in https://github.com/slint-ui/rp-hal/tree/dma-0.6

**Comment by 9names** [comment]
I did a rebase of your rebase earlier today.
https://github.com/9names/rp-hal/tree/dma-0.6
The plan was going to write + run some tests to see what works, maybe clean up the implementation and write some docs

**Comment by ogoffart** [comment]
That would be nice to see that merged. I also tried to upgrade to embedded_dma 0.2 in https://github.com/slint-ui/rp-hal/tree/embedded_dma2 (which i just pushed now),  but i haven't tried it yet.

**Comment by 9names** [comment]
Closed via #457
