### ISSUE TITLE
PIO sideset does not work (wrong pindir)

### ISSUE THREAD

**Issue by mgottschlag** [rp-rs/rp-hal#141]
I tried to write a PIO program that used sideset, but sideset assignments did not have any effect. It turns out that apparently it is necessary to set the pindir of the sideset pins before using them. The documentation calls the function `pio_sm_set_pindirs_with_mask()` for that which takes a 32-bit bitmask and sets the pindir for all currently selected `set` pins according to the mask. The following code is equivalent to that function, to be placed in StateMachine:

    pub fn set_pindirs_with_mask(&self, mut pins: u32, pindir: u32) {
        let mut pin = 0;
        while pins != 0 {
            if (pins & 1) != 0 {
                // Select a single "set" pin.
                self.sm().sm_pinctrl.write(|w| {
                    unsafe {
                        w.set_count().bits(1);
                        w.set_base().bits(pin as u8);
                    }
                    w
                });
                // Execute "set pindir, <dir>", where "dir" is 1 if the pin is in the mask.
                self.sm().sm_instr.write(|w| {
                    unsafe {
                        w.sm0_instr().bits(0xe080 | ((pindir >> pin) & 0x1) as u16);
                    }
                    w
                });
            }
            pin += 1;
            pins = pins >> 1;
        }
    }

This function has the nice sideeffect that it often saves a `set pindir, ...` instruction at the beginning of the program.

I do not know how to properly integrate such a function into the PIO abstraction - the Pico SDK implementation just saves and restores selected pins in that function. That, however, does not work if the state machine is currently active - although, if I understand it correctly, the current PIO abstraction does not try to provide any safeguards against such misuse? Other HALs use a lot more typestates for that.

**Comment by ithinuel** [comment]
As discussed on matrix this [ws2812 driver](https://github.com/ithinuel/ws2812-pio-rs) explicitly adds that instruction in the assembled program (see [line 45](https://github.com/ithinuel/ws2812-pio-rs/blob/main/src/lib.rs#L45)).
This requires to also configure the `set_pins` as visible [line 77](https://github.com/ithinuel/ws2812-pio-rs/blob/main/src/lib.rs#L77). 
It does use an extra instruction that's only used once though. Using type-states to handle the initialization status of the state machine seems like a great idea!
