### ISSUE TITLE
BSPs should handle rp2040_boot2

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#145]
We're currently manually specifying which boot2 to use inside user/example code.
If the BSP exported a bootloader symbol, BSP examples could be generic.
Example
```rust
// alias for the bsp so we don't have to change as much code when changing targets
use feather_rp2040 as target_bsp;
#[link_section = ".boot2"]
#[used]
pub static BOOT2: [u8; 256] = target_bsp::BOOT_LOADER;
```
instead of a different
```rust
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER_GD25Q64CS;
```
for each board

**Comment by 9names** [comment]
An alternative approach was suggested by adamgreig in matrix chat:
A default feature, that when enabled makes the BSPs link rp2040_boot2::BOOT_LOADER for you.
Pros:
- No extra boilerplate in every project, completely invisible to the user.

Cons:
- Being invisible means that if it stops working for whatever reason, it's more painful to fix
- Default features do not spark joy

**Comment by jannic** [comment]
One possible disadvantage (of both approaches):
The build tools necessary to build the bootloader (arm-none-eabi-gcc) may not be easily available everywhere. (Windows?) 
In that case, one can easily include a precompiled boot2, instead:
```
#[link_section = ".boot2"]
#[used]
pub static BOOT2: [u8; 256] = *include_bytes!("boot2.bin");
```
But if `rp2040-boot2-rs` is a dependency of the BSP, one also needs to fork the BSP and remove that dependency.

(Please note that there is already a suggestion to change the boot2 crate so the assembler does not run automatically at build time: https://github.com/rp-rs/rp2040-boot2-rs/pull/2. With that change, my point would be void.)

**Comment by thejpster** [comment]
Nearly there!
