### ISSUE TITLE
PIO example which loads a .pio file

### ISSUE THREAD

**Issue by thejpster** [rp-rs/rp-hal#154]
If you are working with the Pico SDK, you might have some PIO code written out in a .pio file. We should have an example of some Rust code that can load the .pio file at compile time.

**Comment by doraneko94** [comment]
Do you want to add this example to the `examples` in this repository? 
Or is it sufficient since it currently exists in `rp_hal_boards`?

**Comment by ithinuel** [comment]
IMHO, rp-hal-boards is good enough.

**Comment by jannic** [comment]
https://github.com/rp-rs/rp-hal-boards/blob/main/boards/rp-pico/examples/pico_pio_pwm.rs#L132 does exactly that. So I think this ticket can be closed?
