### ISSUE TITLE
GPIO interrupt register accesses may be unsound

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#161]
The pointers used to access GPIO interrupt registers are likely to be unsound (due to pointing outside of the original object).
Check if the original object in the PAC is an array, and if it isn't, convert it to an array then update src/gpio/reg.rs functions to index into it.

_Originally posted by @9names in https://github.com/rp-rs/rp-hal/pull/147#discussion_r723732755_

**Comment by jannic** [comment]
While I still think that the current code is probably sound, it has a different issue: The register access should be volatile.
The change suggested by @9names, using the PAC accessors, would solve that.
