### ISSUE TITLE
Move core PIO functionality into HAL

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#172]
The HAL currently has [pio](https://github.com/rp-rs/pio-rs) in it's dependencies.
It would be nice to have enough of the core functionality inside the HAL that you could choose not to have the `pio` crate as a dependency.
We would need to keep it as a dev-dependency unless we move all PIO examples to a different crate.

Preferably, keep at least enough functionality in the HAL code to bring precompiled PIO programs directly into user code.

Example
```
static const PIO_PROGRAM:[u32;32] = include_str!("blinky.bin");
```
and then in main
```
let (sm, _, _) = rp2040_hal::pio::PIOBuilder::from_program(PIO_PROGRAM)
        .set_pins(led_pin_id, 1)
        .clock_divisor(div)
        .build(sm0);
    sm.start();
```

**Comment by jannic** [comment]
Did some (non-scientific) measurements regarding pio compile time.
Test case: https://github.com/rp-rs/rp2040-project-template
Commands: `cargo clean; time cargo check` (Personally I care more about `cargo check` than about `cargo build --release` duration)
Result with stock rp2040-hal:
```
real    0m22.181s 
user    1m11.374s 
sys     0m5.505s 
```
Results with pio removed (both the dependency on pio-rs and the whole module `pub mod pio`):
```
real    0m21.237s
user    1m1.231s
sys     0m4.752s
```

**Comment by anall** [comment]
> It could be nice if the HAL didn't transitively depend on … `paste`

The HAL itself directly depends on `paste` so the dependency through `pio-rs` is irrelevant.
