### ISSUE TITLE
Safety requirement must be verbosely advertised to not be overlooked in future changes

### ISSUE THREAD

**Issue by ithinuel** [rp-rs/rp-hal#186]
This issue is a follow-up of https://github.com/rp-rs/rp-hal/pull/177

Because of that change ALL further changes in PIO must guaranty that they are atomic and won't break that contract.

The current code isn't verbose enough about that requirement and it will likely be overlooked in coming PRs especially considering that not all peripheral are marked Send and reviewers may not be aware of that requirement.

There need to be a detailed explanation about what that marker implies in terms of safety requirement on `PIO` as well as a `// SAFETY: ` tag on every access to the `PIO`'s register block.

**Comment by jannic** [comment]
@ithinuel what do you think, is this issue sufficiently handled by #190 or are there still important facts missing from the comments?

**Comment by ithinuel** [comment]
That seems right yes. Thank you, I'm closing the issue.
