### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jannic** [rp-rs/rp-hal#215]
There has not been a new release of rp2040-hal for several months. During that time, the crate improved significantly.
With a new release (0.3.0?), it would be much easier for newcomers to find those improvements.

As rp2040-hal depends on [pio](https://github.com/rp-rs/pio-rs), which was not yet released to crates.io, there are a few steps to be taken:

- [x] publish pio to crates.io
- [x] update rp-hal/rp2040-hal to depend on the released version of pio
- [x] publish updated version of rp2040-hal
- [x] Update changelog before tagging the release

**Comment by 9names** [comment]
One more task so I don't forget:
- [ ] Update changelog before tagging the release

**Comment by thejpster** [comment]
embassy-rs is blocking us doing a release, because rp-hal git depends on embassy-traits.

**Comment by thejpster** [comment]
Asked about it in https://github.com/embassy-rs/embassy/issues/549

**Comment by thejpster** [comment]
Doesn't it complain that embassy-traits isn't a feature any more?

**Comment by thejpster** [comment]
Apparently not...

**Comment by thejpster** [comment]
https://github.com/rp-rs/rp-hal/pull/242

**Comment by thejpster** [comment]
Done!
