### ISSUE TITLE
Multicore: sio.fifo.write() doesn't wake other core

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#222]
sio.fifo.read_blocking() puts the current core to sleep.
sio.fifo.write_blocking() pushes a character, then sends a signal to wake the other core.
sio.fifo.write() does not send a wake signal, so the reading core will stay asleep forever.

Do we want to keep this functionality?
It's definitely a foot gun, the first example I wrote was broken by the assumption that write would wake the other core if it was blocking.

**Comment by jannic** [comment]
I'd definitely add the `cortex_m::asm::sev();` to `sio.fifo.write()`.
It's also what I would expect without reading the code. And I don't see any reason not to add it.
