### ISSUE TITLE
Review ```/// #Safety``` comments from PR #223

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#225]
#223 was merged without a reviewer so that further PRs could have CI green.
Please review the safety comment and verify that it makes sense in this context

_Originally posted by @9names in https://github.com/rp-rs/rp-hal/issues/223#issuecomment-985487453_

**Comment by jonathanpallant** [comment]
Looks OK to me.

**Comment by 9names** [comment]
Closing this then, thanks for the review
