### ISSUE TITLE
Interrupt Driven UART Read Example/HAL

### ISSUE THREAD

**Issue by camrbuss** [rp-rs/rp-hal#234]
None of the UART examples currently use any of the read portions of the hal, nor does it currently seem possible to have interrupt driven reads.

If someone has worked this, or I am missing something, please let me know.

**Comment by thejpster** [comment]
I started https://github.com/rp-rs/rp-hal/tree/uart_irq_example to think about the options here.

**Comment by camrbuss** [comment]
Wow, awesome!

I certainly like Option 2 and Option 3. I opened this with the idea that enabling the rx interrupts and using rtic would meet my needs.

In general, what you added to `rp2040-hal/examples/uart_interrupt.rs`, will open up ways of showing any of the options.

**Comment by thejpster** [comment]
Merged #247
