### ISSUE TITLE
Provide faster access to ROM functions

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#238]
Our current method of accessing ROM functions involves a ROM table walk to find the correct function first.
A few options we could pursue:
- Store a function-pointer table in flash for each variant of the ROM - check ROM version on each call then jump to correct table
- Static function pointer in each of the wrapper functions, initialized by ROM table walk on first use
- Reserve space in linker file for RAM table, initialize entire table in rt, [#entry], or first use

**Comment by thejpster** [comment]
I don't like option 1. It seems this lookup was precisely to avoid caring about the ROM version.

I feel like it's something you should opt into at the very least. My preferred option is two functions for every ROM function - one does the work, and one gets you a function pointer if you want to cache the result and call the function pointer yourself in a tight loop.
