### ISSUE TITLE
UartConfig cannot be constructed

### ISSUE THREAD

**Issue by VictorKoenders** [rp-rs/rp-hal#253]
Commit bdfb4d82c9c9d1d2f9f23c45f4d03132e7f2b962 made the `UartConfig` `#[non_exhaustive]`. This means that users of this crate cannot actually construct an instance of this type.

There are a couple of solutions for this that I can see:
1. Remove the `#[non_exhaustive]`
1. Add `impl Default`, with the following defaults:
   ```rs
   impl Default for UartConfig {
       fn default() -> Self {
           Self {
               baudrate: Baud(0),
               data_bits: DataBits::Eight,
               stop_bits: StopBits::One,
               parity: None,
           }
       }
   }
   ```
1. Expect people to take a `uart::common_configs` instance and modify that. e.g:
    ```rs
    let mut config = common_configs::_115200_8_N_1;
    config.baudrate = Baud(0);
    ```
1. Introduce a builder pattern  (Probably not preferred, but still worth a mention)

**Comment by thejpster** [comment]
I'm sure we discussed this ... but I can't remember if it was in another issue, in a PR, or on Matrix. Any ideas?

But yes, it needs fixing and I suggest `impl Default for UartConfig` is probably the best approach.
