### ISSUE TITLE
Spinlocks not cleared by reset

### ISSUE THREAD

**Issue by jannic** [rp-rs/rp-hal#292]
When flashing a new firmware with `probe-run`, the automatically executed reset doesn't clear the spinlocks. Therefore, if (for example) the spinlock used for critical sections was locked at the moment when `probe-run` interrupted the running program, the new firmware will deadlock as soon as it tries to acquire the spinlock. The same is true for a `sys_reset()`.

Possible workaround: Adding `(*pac::SIO::ptr()).spinlock[number_of_spinlock].write(|w| w.bits(0));` at the top of `main`.

Small program demonstrating the issue:
```
use bsp::hal::sio::Spinlock0;

#[entry]
fn main() -> ! {
    //unsafe { (*pac::SIO::ptr()).spinlock[0].write(|w| w.bits(0)); }
    info!("Program start");
    let _l0 = Spinlock0::claim();
    info!("Lock claimed");
    cortex_m::asm::delay(10000);
    cortex_m::peripheral::SCB::sys_reset();
}
```
Is there a way to solve this cleanly without a custom `#[entry]` macro or some `#[pre_init]` code?

**Comment by jannic** [comment]
This could be a way to solve this issue: https://github.com/jannic/rp2040-entry/blob/master/src/lib.rs#L32-L34

Basically, provide an alternative `#[entry]` attribute, which forwards to `#[cortex_m::entry]` but adds code to release all spinlocks at program start.

For simplicity, I just added another wrapper function. This becomes visible in backtraces:
```
stack backtrace:
   0: rp2040_project_template::__rp2040_entry_main
        at src/main.rs:75:5
   1: rp2040_project_template::__cortex_m_rt___rp2040_entry_main_trampoline
        at src/main.rs:59:1
   2: main
        at src/main.rs:59:1
   3: Reset
```
It would probably be possible to inject the added code into `fn main()` or into the trampoline added by `cortex_m_rt`, instead.

**Comment by jannic** [comment]
Updated the [example](https://github.com/jannic/rp2040-entry/) so it injects the unlocking code directly into `main()`.

**Comment by thejpster** [comment]
Good catch!

I was already thinking about BSP entry functions, so a HAL entry is not unreasonable.

Does it get inlined in release mode using LTO?

**Comment by jannic** [comment]
The latest version of the example directly injects the code into main, so there is no need to inline anything, and LTO doesn't matter.
(Well with opt-level 0, the iterator stuff from `for i in 0..SPINLOCK_COUNT` is still present, but I guess that's to be expected.)

With `opt-level = "z"` it gets compiled to just a few instructions ("s" is similar, 1 instruction longer):
```
100001fc: 00 21         movs    r1, #0
100001fe: 05 48         ldr     r0, [pc, #20] <$d.2+0x2>
10000200: 01 22         movs    r2, #1
10000202: 0a 50         str     r2, [r1, r0]
10000204: 09 1d         adds    r1, r1, #4
10000206: 80 29         cmp     r1, #128
10000208: fa d1         bne     0x10000200 <rp2040_project_template::__cortex_m_rt_main::hb23e90f4068b4560+0x4> @ imm = #-12
[...]
10000214 <$d.2>:
10000214:       00 01 00 d0     .word   0xd0000100
```
However, with opt-levels 1 and 2 the loop gets unrolled. For level 2 it becomes:
```
100001fc: 17 48         ldr     r0, [pc, #92] <$d.2>
100001fe: 01 21         movs    r1, #1
10000200: 01 60         str     r1, [r0]
10000202: 41 60         str     r1, [r0, #4]
10000204: 81 60         str     r1, [r0, #8]
10000206: c1 60         str     r1, [r0, #12]
10000208: 01 61         str     r1, [r0, #16]
1000020a: 41 61         str     r1, [r0, #20]
1000020c: 81 61         str     r1, [r0, #24]
[...]
1000023e: c1 67         str     r1, [r0, #124]
```
So it takes 68 bytes at opt-level 2, 16 bytes at "s" and 14 bytes at "z". Opt-levels 0 and 1 are much worse.

Interestingly, opt-level 2 also unrolls the loop of `Spinlock0::claim()` four times (not part of the `#[entry]` code, but of my testing binary):
```
10000240: 01 68         ldr     r1, [r0]
10000242: 00 29         cmp     r1, #0
10000244: 08 d1         bne     0x10000258 <rp2040_project_template::__cortex_m_rt_main::hba8cd7f3c9c96993+0x5c> @ imm = #16
10000246: 01 68         ldr     r1, [r0]
10000248: 00 29         cmp     r1, #0
1000024a: 05 d1         bne     0x10000258 <rp2040_project_template::__cortex_m_rt_main::hba8cd7f3c9c96993+0x5c> @ imm = #10
1000024c: 01 68         ldr     r1, [r0]
1000024e: 00 29         cmp     r1, #0
10000250: 02 d1         bne     0x10000258 <rp2040_project_template::__cortex_m_rt_main::hba8cd7f3c9c96993+0x5c> @ imm = #4
10000252: 01 68         ldr     r1, [r0]
10000254: 00 29         cmp     r1, #0
10000256: f3 d0         beq     0x10000240 <rp2040_project_template::__cortex_m_rt_main::hba8cd7f3c9c96993+0x44> @ imm = #-26
```
Great, a performance "optimization" of a loop spinning for some lock. :joy:
