### ISSUE TITLE
Anyone is using WSL for developing, cargo run can't find mounted RPI-RP2.

### ISSUE THREAD

**Issue by HughGrant** [rp-rs/rp-hal#308]
I am setting up my whole dev env in WSL Ubuntu 20.04, Because you know you'll be f*cked up if you set it up in Windows.
So far, everything works great, stuck at the last step.
I do have my rp pi pico BOOTSEL connected to my computer, and it showed up in window, but the cargo run seems unable to located it.
I know it's more like a feature request, but has anyone actually know how to bypass this?
It could be related to elf2uf2-rs crate though.

**Comment by 9names** [comment]
> Because you know you'll be f*cked up if you set it up in Windows.

I've set up native Rust on Windows for work, and on a test machine for this project.
rp-hal builds fine, elf2uf2 works and can install to a mounted Pico.
It's not my first choice for a development environment, but it is viable.

> I know it's more like a feature request, but has anyone actually know how to bypass this?

If you can get your Pico drive mount to appear in the right place inside of WSL, maybe it would already work?
This is a common problem when using WSL and trying to access hardware natively.

elf2uf2 uses the `sysinfo` crate to find disks.
check out the examples to see if it can find your Pico drive mount via it's name `RPI-RP2`,
or can find a disk with a file named `INFO_UF2.TXT` inside of it.

If you can't make the Pico appear as a drive mount under WSL, there's not much that we could do to fix this.
You could manually copy the elf file onto your Windows filesystem and run elf2uf2 on it from there, or you could copy the file yourself.
But I think the easiest answer is to try out a native rust install - you might be surprised at how easy it is to build and run Rust projects.

**Comment by HughGrant** [comment]
> > Because you know you'll be f*cked up if you set it up in Windows.
> 
> I've set up native Rust on Windows for work, and on a test machine for this project. rp-hal builds fine, elf2uf2 works and can install to a mounted Pico. It's not my first choice for a development environment, but it is viable.
> 
> > I know it's more like a feature request, but has anyone actually know how to bypass this?
> 
> If you can get your Pico drive mount to appear in the right place inside of WSL, maybe it would already work? This is a common problem when using WSL and trying to access hardware natively.
> 
> elf2uf2 uses the `sysinfo` crate to find disks. check out the examples to see if it can find your Pico drive mount via it's name `RPI-RP2`, or can find a disk with a file named `INFO_UF2.TXT` inside of it.
> 
> If you can't make the Pico appear as a drive mount under WSL, there's not much that we could do to fix this. You could manually copy the elf file onto your Windows filesystem and run elf2uf2 on it from there, or you could copy the file yourself. But I think the easiest answer is to try out a native rust install - you might be surprised at how easy it is to build and run Rust projects.

first of all, thank you so much for putting time to this.
Yes, I already started trying to set up a native windows dev env, this is currently the best way.
again, thank you so much.
