### ISSUE TITLE
Running tests on CI

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#33]
After merging PR https://github.com/rp-rs/rp-hal/pull/29 we started running `cargo test` on the CI host
This CI stage started failing on https://github.com/rp-rs/rp-hal/pull/24 with error message: Error: language item required, but not found: `eh_personality`
Link to CI failure https://github.com/rp-rs/rp-hal/pull/24/checks?check_run_id=2498172416

We would like to run tests that exercise embedded_hal traits, but these will not run in CI without providing them.
I could not find any other HAL attempting to run cargo test on the hosts CI, there are security/reliability issues with running HIL(hardware-in-loop) with CI on one of the developers systems, and I don't think linux-embedded-hal is sufficiently advanced that we can use it for this purpose.

My current proposal is that we stop running `cargo test` as part of CI until we can determine how to do so without causing more harm than good.
I've created a PR https://github.com/rp-rs/rp-hal/pull/32 that does that, as well as breaking our current CI workload into multiple workflows to aid discovery

**Comment by tdittr** [comment]
My main motivation for running the tests in the CI is to verify that the doctest examples actually compile.

Secondary would be unit tests for calculations like the startup delay in the XOSC.

Running Hardware-In-the-Loop tests would be nice but I dont't think we can run them in the CI without significant effort. Though a HIL testsuite would be nice to run locally from time to time.

> We would like to run tests that exercise embedded_hal traits, but these will not run in CI without providing them.

I think you mix something up here. `rp-hal` implements the embedded-hal traits and does not use them. 

Maybe we need to activate std for running tests? Like in this [example](https://ferrous-systems.com/blog/test-embedded-app/#accessing-std-when-testing-embedded-code-testing-host2target):
```rust
#![cfg_attr(not(test), no_std)]
```

I can try this tomorrow :)
