### ISSUE TITLE
Any way to use STD libraries with the rp-hal?

### ISSUE THREAD

**Issue by alxpettit** [rp-rs/rp-hal#343]
Is there any way to use STD libraries with this HAL?

**Comment by 9names** [comment]
A HAL cannot provide STD, you need to choose a target that supports it.
At the moment, the only Rust target that does this is esp-idf which supports the esp32, esp32-c and esp32-s families.

https://esp-rs.github.io/book/overview/using-the-standard-library.html
https://github.com/esp-rs/esp-idf-hal

**Comment by alxpettit** [comment]
Gotcha :ok_hand:  thankies :)
