### ISSUE TITLE
Blinky.rs doesn't work

### ISSUE THREAD

**Issue by weihsiu** [rp-rs/rp-hal#37]
the blinky example in rp2040-hal doesn't seem to work.  the example compiled just fine.  and after converting it to .uf2 and move it to a pico board, the led on pin 25 doesn't blink at all.

**Comment by 9names** [comment]
I just did a build of the latest HAL, and it worked first go.
Have you run rustup recently, maybe running a newer version of rustc might help?
Here's my commands, in case there's something I'm doing that isn't obvious.
```
>rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
>cargo build --example blinky --release
>elf2uf2 target/thumbv6m-none-eabi/release/examples/blinky blinky.uf2
>cp blinky.uf2 /media/9names/RPI-RP2/
```
