### ISSUE TITLE
flash_range_program() and flash_range_erase() functions are not working separately

### ISSUE THREAD

**Issue by abhishekdhamale** [rp-rs/rp-hal#377]
I am trying to use flash_range_erase() and flash_range_program() separately in different functions but its not working. Further if data is more than 4096 bytes after writing, if I try to read using probe-rs-cli then gets only 0x0000000 in every word on the flash.

**Comment by abhishekdhamale** [comment]
added delay before erasing and writing

**Comment by jannic** [comment]
Did you happen to use defmt-rtt when the problem happened?
Might be related to https://github.com/knurling-rs/defmt/pull/683

**Comment by abhishekdhamale** [comment]
> Did you happen to use defmt-rtt when the problem happened? Might be related to [knurling-rs/defmt#683](https://github.com/knurling-rs/defmt/pull/683)

yes I was using defmt statements.
