### ISSUE TITLE
Documentation error in rp2040_hal::pio::Rx

### ISSUE THREAD

**Issue by Schmeckinger** [rp-rs/rp-hal#384]
pub fn is_empty(&self) -> bool
Indicate if the tx FIFO is full

https://docs.rs/rp2040-hal/0.5.0/rp2040_hal/pio/struct.Rx.html#method.is_empty

**Comment by Schmeckinger** [comment]
Also there is no is_full(), idk if thats on purpose. The pac has a rxfull() so it should be trivial to implement. Should I open a new issue for this?

**Comment by jannic** [comment]
You are right. This is known and already fixed: https://github.com/rp-rs/rp-hal/pull/367/commits/bee91352c1b5498b74eebc8af3b427b0272f8c55
The documentation on docs.rs shows the latest release, which doesn't contain the fix yet.
