### ISSUE TITLE
`gpio::Disabled` does not implement `NonPwmPinMode`

### ISSUE THREAD

**Issue by FlorianUekermann** [rp-rs/rp-hal#397]
I get the following compile time error, if I try to reset a pin to `PullDownDisabled` using `into_mode` on a `PwmPinToken`:

```
the trait `NonPwmPinMode` is not implemented for `rp_pico::rp2040_hal::gpio::Disabled<rp_pico::rp2040_hal::gpio::PullDown>
```

I am using `pwm_pin_token.into_mode::<ReadableOutput>().into_mode()` as  a workaround. It seems to me that there's just an `impl` missing. Happy to send a pull request if I'm not misunderstanding what is going on.

**Comment by 9names** [comment]
Yes, it seems to be just missing that impl. PR would be great, thanks!
