### ISSUE TITLE
Broken homepage link on crates.io

### ISSUE THREAD

**Issue by eutampieri** [rp-rs/rp-hal#42]
Cargo.toml has a broken link, so the homepage link on crates.io gives a 404

**Comment by 9names** [comment]
Which link is it in Cargo.toml that is broken?

**Comment by eutampieri** [comment]
https://github.com/eolder/RP2040-hal

**Comment by 9names** [comment]
This was updated in the latest release, but is unfortunately still wrong.
https://github.com/rp-rs/rp-hal/blob/d4ec87b2f7950db71a47155beb224cbbc6968eb3/rp2040-hal/Cargo.toml#L6
needs to change to
https://github.com/rp-rs/rp-hal
