### ISSUE TITLE
Creating UART with custom baud rate is not ergonomic

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp-hal#470]
This is essentially https://github.com/rp-rs/rp-hal/issues/253 again, as the fix in #268 doesn't fix the original issue.

So there's a few problems here:
- No example using anything other than a default baud rate or one of the common_configs
- No documentation explaining how to get a custom baud rate
Even if you do manage to get it working, you're left with
```rust
let mut uartconf = bsp::hal::uart::common_configs::_9600_8_N_1;
uartconf.baudrate = HertzU32::from_raw(4800);
```
which is very surprising from an ergonomics point of view. the way to set UART config should be more ergonomic than this, even with "uncommon" configs.

Possible solutions:
- Remove [non_exhaustive] from the config struct so you can initialise it by struct
- Add a constructor that takes all the arguments in one pass
- Use a builder pattern constructor that starts with default::Default and allows each setting to be modified one at a time. This assumes that Default is actually most often what users want, maybe we shouldn't do that.

**Comment by jannic** [comment]
What I don't like about the builder pattern together with `default::Default` is that this hides the actually used values. Reader of source code where such a config is created need to remember or look up what `default::Default()` means to understand the code.

The `new` constructor is implemented in https://github.com/rp-rs/rp-hal/pull/471.

(And also some functions which can be used in a builder pattern - so developers with different preferences could use that as well.)
