### ISSUE TITLE
PwmPinToken makes using GPIO interrupts unergonomic while providing relatively little safety

### ISSUE THREAD

**Issue by dlkj** [rp-rs/rp-hal#542]
I propose we drop `rp2040_hal::pwm::PwmPinToken` and have `pwm::Slice::output_to()` and `pwm::Channel::input_from()` return the `Pin` with its `PinMode` set to `FunctionPwm`.

# Why?

`PwmPinToken` blocks access to the `Pin` interrupt and pad configuration methods once the pin is being used with a PWM Slice. You may want to use and edge triggered GPIO interrupt with the PWM Slice to measure a pulse width via in interrupt handler. Edge interrupts must be explicitly cleared, this isn't possible due to the wrapping of the `Pin` by `PwmPinToken`.

# Work around

You can work round this by extracting the `Pin` from the `PwmPinToken` then reconnecting it to the PWM Slice/Channel by setting the pin mode manually:

```rust
let pwm_slices = pwm::Slices::new(pac.PWM, &mut pac.RESETS);

let mut pwm: pwm::Slice<_, pwm::InputHighRunning> = pwm_slices.pwm0.into_mode();
pwm.enable();

let channel = &mut pwm.channel_b;

let input_pin: gpio::Pin<_, gpio::PullUpDisabled> = channel.input_from(pins.gpio1).into_mode();
let input_pin: gpio::Pin<_, gpio::FunctionPwm> = input_pin.into_mode();

input_pin.set_interrupt_enabled(gpio::Interrupt::EdgeLow, true);
```

This also demonstrates that the `PwmPinToken` isn't really achieving any safety, it's just reducing the ergonomics of valid uses of a `Pin`.

# Changes

I've created #541 to remove `PwmPinToken` and add an example demonstrating how to use the PWM Slice and GPIO interrupts together.

**Comment by jannic** [comment]
Fixed with #541
