### ISSUE TITLE
Timer from cvr register (SysTick)

### ISSUE THREAD

**Issue by IridiumXOR** [rp-rs/rp-hal#553]
Hi,
can I read CVR register (SysTick) in order to have a nanoseconds passed from boot up? It can be very useful to have a timer based on it..

**Comment by jannic** [comment]
Reading CVR is possible using the cortex_m crate, no need to support it from the HAL:
```
cortex_m::peripheral::SYST::get_current();
```

**Comment by jannic** [comment]
Perhaps also useful: The [rom_funcs example](https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/examples/rom_funcs.rs) is using it to perform some timings.

**Comment by IridiumXOR** [comment]
Yes thank you, for reference [here](https://forums.raspberrypi.com/viewtopic.php?t=333928) there is an interesting discussion about SysTick
