### ISSUE TITLE
UART example

### ISSUE THREAD

**Issue by Szpadel** [rp-rs/rp-hal#62]
Hi,

Can anyone provide example for setting up UART?
I'm having issue that I located (using led) to be in `UartPeripheral::enable` (code probably panics or hangs the cpu)
I located that it cannot be invalid frequency (as I didn't unwrap error) and I didn't found anything obvious inside that could cause that.

Thanks

**Comment by Szpadel** [comment]
I debugged that it hangs in this loop:
https://github.com/rp-rs/rp-hal/blob/148cc2b8ea83cfb035ff6abd76dbe43e6b7c1bc8/rp2040-hal/src/resets.rs#L19

Any hints why it might not go from reset?

**Comment by leo60228** [comment]
I haven't tested this myself, but did you call `init_clocks_and_plls`? That's a pretty simple thing, but comparing the rp-hal and pico-sdk code, that's the only thing I could think of...

pico-sdk has a check to make sure clk_peri is enabled before initializing the UART.
