### ISSUE TITLE
Release 0.9.0?

### ISSUE THREAD

**Issue by oOMelon** [rp-rs/rp-hal#634]
Hi, is it possible to release version 0.9.0? I'm in need of InOutPin on gpio. Cloning source and including turned into a lot of overhead and other issues that I'd rather not deal with if a new release is possible :)

So is it possible? Or should I try to fix the issues by working with source?

Thanks in advance!

**Comment by 9names** [comment]
The recommend way to deal with unreleased versions is to have a `patch.crates-io` section in your cargo.toml.
It's much easier than cloning and including.
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#prepublishing-a-breaking-change

**Comment by oOMelon** [comment]
Aha! I didn't know about that! Thanks for the information I'll try that later today
