### ISSUE TITLE
pio clock speed dmx

### ISSUE THREAD

**Issue by JonasFocke01** [rp-rs/rp-hal#637]
Hello,

first of all, thank you for writing this! I had a blast programming the pico with rust, bringing my ws2812b led strip to life and doing some button trickery!  
But the issue im facing now seems to be a bit more tricky, as i try to read DMX via a pio sm. The inputs are configured correctly, i have confirmed that with an arduino, so it must be something in my code..  
The pio assembly comes from [jostlowe](https://github.com/jostlowe) and is working correctly in his c++ library.  
```
.program DmxInput
.define dmx_bit 4                     ; As DMX has a baudrate of 250.000kBaud, a single bit is 4us

break_reset:
    set x, 29                         ; Setup a counter to count the iterations on break_loop

break_loop:                           ; Break loop lasts for 8us. The entire break must be minimum 30*3us = 90us
    jmp pin break_reset               ; Go back to start if pin goes high during the break
    jmp x-- break_loop   [1]          ; Decrease the counter and go back to break loop if x>0 so that the break is not done
    wait 1 pin 0                      ; Stall until line goes high for the Mark-After-Break (MAB)

.wrap_target
    wait 0 pin 0                      ; Stall until start bit is asserted
    set x, 7             [dmx_bit]    ; Preload bit counter, then delay until halfway through

bitloop:
    in pins, 1                        ; Shift data bit into ISR
    jmp x-- bitloop      [dmx_bit-2]  ; Loop 8 times, each loop iteration is 4us
    wait 1 pin 0                      ; Wait for pin to go high for stop bits
    in null, 24                       ; Push 24 more bits into the ISR so that our one byte is at the position where the DMA expects it
    push                              ; Should probably do error checking on the stop bits some time in the future....

.wrap
```

I have tried to install it in a pio sm, and it compiles  
```
let program_with_defines = pio_proc::pio_file!("DmxInput.pio", select_program("DmxInput"),);
    let (mut pio, sm0, _, _, _) = pac.PIO0.split(&mut pac.RESETS);
    let installed = pio.install(&program_with_defines.program).unwrap();
    let (mut sm, mut rx, tx) = rp2040_hal::pio::PIOBuilder::from_program(installed)
        .jmp_pin(22)
        .in_pin_base(22)
        .clock_divisor_fixed_point(520, 0)
        .autopull(true)
        .build(sm0);
    sm.start();
```
But when i now read it, it seems to be only garbage. (i have a Serial_Port setup and writing the data directly to it.) 
```
        if let Some(channel) = rx.read() {
            channel.to_le_bytes().iter().for_each(|channel| {
                if *channel != 0 {
                    serial.write(&channel.to_le_bytes());
                }
            });
        }
```
I suspect, that the issue lies somwhere in my clock calculation. Am i calculating nonsense?
I have tried both (to_le_bytes and to_be_bytes), but without luck.
Other than that, im a bit out of ideas what it could be..  
Any hint would be greatly appreciated!

**Comment by nilclass** [comment]
> I suspect, that the issue lies somwhere in my clock calculation. Am i calculating nonsense?

@JonasFocke01 Could you share your calculation, and what clock frequency you expect?
The cpp code calculates `sys_clk / 1000000` [here](https://github.com/jostlowe/Pico-DMX/blob/main/src/DmxInput.cpp#L86C44-L86C55). Assuming sys_clk is 125MHz, the divisor would be 125, not 520.
