### ISSUE TITLE
USB set_device_address 

### ISSUE THREAD

**Issue by mrdxxm** [rp-rs/rp-hal#638]
Hello. I've been looking at the code in src/usb.rs and found that this function writes only 6 out of 7 bits of usb address (& 0x3F instead of & 0x7F)
Maybe I don't know something, but it looks like a bug.

https://github.com/rp-rs/rp-hal/blob/08f5e0f88b0734f93a3a11c172e566f571863dc2/rp2040-hal/src/usb.rs#L550C5-L561C6

**Comment by ithinuel** [comment]
That is a good catch ! 
Could you open a PR to fix it? :)

**Comment by mrdxxm** [comment]
#639
