### ISSUE TITLE
Arithmetic mistake setting up core1 stack protection

### ISSUE THREAD

**Issue by dfoxfranke** [rp-rs/rp-hal#641]
This line:

https://github.com/rp-rs/rp-hal/blob/b1eea90ebe779409ea63ccb21291c11f8b684561/rp2040-hal/src/multicore.rs#L70

looks slightly wrong, as the `0x8` makes no sense. 0x8 is bit 3 of `REGION`. I think you meant to be setting the `VALID` bit, which would be `0x10`, and to have `REGION` be 0. As it is, `VALID` is 0 and `REGION` is 8. When `VALID=0`, `REGION` is ignored and the region is instead taken from the current value of `MPU_RNR`. Since `MPU_RNR` happens to be zero at the time this function is called, it still accidentally does the right thing.

**Comment by 9names** [comment]
That code was taken from pico-sdk, where this bug was already documented in https://github.com/raspberrypi/pico-sdk/issues/993 and fixed in https://github.com/raspberrypi/pico-sdk/pull/1180
Good catch!
