### ISSUE TITLE
Printing to USB?

### ISSUE THREAD

**Issue by EricLBuehler** [rp-rs/rp-hal#652]
Hello everybody,

I am designing a small project and was trying to output status via serial. I have previously done this in C, so the Pico is able to. However, I cannot find how to do it with rp-hal. How should I print to the USB serial connection?

Thank you!

**Comment by nilclass** [comment]
I highly recommend reading the examples, which can be found here: https://github.com/rp-rs/rp-hal-boards/tree/main/boards/rp-pico/examples

In this case the [pico_usb_serial example](https://github.com/rp-rs/rp-hal-boards/blob/main/boards/rp-pico/examples/pico_usb_serial.rs) should cover what you are looking for.

**Comment by EricLBuehler** [comment]
Okay, thanks :)
