### ISSUE TITLE
Watchdog timer set to garbage

### ISSUE THREAD

**Issue by Szpadel** [rp-rs/rp-hal#72]
It looks like watchdog is configured incorrectly in `init_clocks_and_plls`
https://github.com/rp-rs/rp-hal/blob/ffa97842e295b19a01fb6438f700c683e9d90ce1/rp2040-hal/src/clocks/mod.rs#L320

in datasheet it is that it should work at 1MHz (and alarms are using the same clock), therefore this should be set here to:
`(xosc_crystal_freq / 1_000_000) as u8`
currently it is trying write very big number (12MHz) to 8bits and as it is truncated it sets it to garbage value

**Comment by 9names** [comment]
Nice catch. This logic checks out.
This is also essentially how the C SDK does it - they pass `XOSC_MHZ` which is declared as `#define XOSC_MHZ 12` to their equivalent of this function.
