### ISSUE TITLE
slow startup of XOSC

### ISSUE THREAD

**Issue by laenzlinger** [rp-rs/rp-hal#745]
I am working on custom board which uses RP2040.

My firmware, developed with rp-rs hal has now issues to boot.  For more details see https://forums.raspberrypi.com/viewtopic.php?p=2174882

I was able to reproduce it with a simple blink.uf2 program built with pico-sdk

The solution with pico-sdk was to configure the startup delay multiplier to 10 (default is 1) 

```
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 10
```

This fixed the startup issues.

Can I apply a similar configuration to the rp2040 hal?

**Comment by jannic** [comment]
Currently it is not easily possible, as far as I can tell. I prepared a small patch (#746) that would add the needed parameter.
