### ISSUE TITLE
ADC read blocks

### ISSUE THREAD

**Issue by chrontax** [rp-rs/rp-hal#780]
Reading an ADC pin blocks for a very long time, at least a second.

ADC setup:
```rs
let adc = Adc::new(pac.ADC, &mut pac.RESETS);
let pin1 = AdcPin::new(pins.gpio26).unwrap();
let pin2 = AdcPin::new(pins.gpio27).unwrap();
let pin3 = AdcPin::new(pins.gpio28).unwrap();
```

Usage:
```rs
buf = [
    adc.read(&mut pins.1).unwrap(),
    adc.read(&mut pins.2).unwrap(),
    adc.read(&mut pins.3).unwrap(),
];
```

**Comment by chrontax** [comment]
After switching from git to latest on crates-io it works

**Comment by jounathaen** [comment]
I have almost the same problem both with git-latest and crates.io  _v0.10.0_. Only difference is, that blocks indefinitely.

The problem doesn't appear in _v0.9.0_.

**Comment by chrontax** [comment]
I didn't know 0.10 released. I'm using 0.9.2 and don't plan on switching for the time being since everything works.
