### ISSUE TITLE
Embassy-RP and RP2040-hal Compatibility??? - Embedded_Hal::PWM:SetDutyCycle Assistance

### ISSUE THREAD

**Issue by Token-Thinker** [rp-rs/rp-hal#816]
Hello All,

I'm building a project based on `embedded-hal` and `embassy` for various boards that does async operations. 
When doing research I noticed that the `embassy-rp` crate doesn't expose the `channel` functionality for setting the duty cycle using `embedded-hal`. 

However `rp2040-hal` does expose that feature, but doesn't seem to have any ties to embassy, which leads to my issue/question.

Will `rp2040-hal` work with `embassy` and are there any potential plans on merging the two?

**Comment by 9names** [comment]
> Will rp2040-hal work with embassy

No. Don't mix HALs.

> are there any potential plans on merging the two?

No. These projects are never going to merge. Feel free to copy the implementation from rp2040-hal over to embassy-rp

**Comment by ithinuel** [comment]
> No. These projects are never going to merge. Feel free to copy the implementation from rp2040-hal over to embassy-rp

But be mindful of licences & a little attribution note wouldn't hurt either.

**Comment by Token-Thinker** [comment]
What do you recommend than for async functionality when using rp-hal?

**Comment by ithinuel** [comment]
I'd recommend, if you have the time and energy, to try to contribute the implementation of the drivers you need :)
I did that for i2c because I'm using it in a project of mine. I intend to do that for PIO at some point but I have a bunch of thing to do that are higher in priority.
