### ISSUE TITLE
Support the ReadReady and WriteReady traits on UART

### ISSUE THREAD

**Issue by nils-van-zuijlen** [rp-rs/rp-hal#821]
The [ReadReady](https://docs.rs/embedded-io/0.6.1/embedded_io/trait.ReadReady.html) and [WriteReady](https://docs.rs/embedded-io/0.6.1/embedded_io/trait.WriteReady.html) traits make generic checking of UART buffers possible.

As there already exist a [uart_is_readable](https://docs.rs/rp2040-hal/latest/rp2040_hal/uart/struct.UartPeripheral.html#method.uart_is_readable) and [uart_is_writable](https://docs.rs/rp2040-hal/latest/rp2040_hal/uart/struct.UartPeripheral.html#method.uart_is_writable) methods, I would hope it would be possible to implement them.

I can make a PR if you want.

**Comment by jannic** [comment]
Sounds like a good idea, and a PR would of course be welcome.

**Comment by Sympatron** [comment]
This was done in #837 and #841.
