### ISSUE TITLE
rp235x-hal PIO is missing `in_count` in SMx_SHIFTCTRL

### ISSUE THREAD

**Issue by allexoll** [rp-rs/rp-hal#867]
all the others fields are configurable in the builder, but this one is not, I believe because it was missed since the register is split on 2 pages (945-946).

**Comment by jannic** [comment]
FJOIN_RX_PUT, FJOIN_RX_GET are also missing. So it's most likely that the builder was not yet updated for the new fields RP235x provides comparted to RP2040.
